[repository]
name = "hyprland-scroll-overview"
authors = ["yayuuu"]
commit_pins = [
    # Hyprland                                  hyprland-scroll-overview
    ["521ece463c4a9d3d128670688a34756805a4328f", "0f47e5657ec3e4e5ffe85ddefd6c62d68f469298"], # v0.54.3
]

[scrolloverview]
description = "A scrollable overview plugin for Hyprland."
authors = ["yayuuu"]
output = "scrolloverview.so"
build = [
    "make all",
]
