[repository]
name = "hyprland-scroll-overview"
authors = ["yayuuu"]
commit_pins = [
    # Hyprland                                  hyprland-scroll-overview
    ["521ece463c4a9d3d128670688a34756805a4328f", "1a4951db70f04ccad9ee2538b94e747c838b215a"], # v0.54.3
]

[scrolloverview]
description = "A scrollable overview plugin for Hyprland."
authors = ["yayuuu"]
output = "scrolloverview.so"
build = [
    "make all",
]
